### PR TITLE
Ui overhaul

### PR DESCRIPTION
**Pull request by omegahm**
I gave the UI a general overhaul. Hope you guys like it.

This pull-request includes features such as:

- [x] Introduced CSS file
- [x] Decluttered CSS and HTML
- [x] Moved scripts to bottom of page
- [x] Use logo as favicon
- [x] Use Bootstraps classes
- [x] Got rid of Bootstrap theme

## "Front page"
screen shot 2015-02-11 at 22 23 48

#### and with Jim active
screen shot 2015-02-11 at 22 24 50

## HTML mail
screen shot 2015-02-11 at 22 23 44

## Modal
screen shot 2015-02-11 at 22 24 01

### CODE REVIEW

**Comment by omegahm** [comment]
I couldn't figure out if I was meant to commit the `assets/assets.go`-file as well, so I left that one out.

**Comment by ian-kent** [comment]
That looks awesome, thanks @omegahm 

Sorry I haven't had time to look properly yet - I'll try and get it merged and a release out tonight!

Thanks :smile:

**Comment by ian-kent** [comment]
(p.s., `assets.go` should be included since it enables `go get` commands to work, but no prob, it'll get rebuilt when I publish a release anyway :panda_face:)

**Comment by omegahm** [comment]
I'll add the `assets.go` to this pull-request once I get home :+1:

**Comment by ian-kent** [comment]
Awesome, thank you!!!! Looks much cleaner :+1:

**Comment by thaJeztah** [comment]
Oh, wow, merged already!

Awesome job, @omegahm!

**Comment by omegahm** [comment]
You are very welcome. We just started using MailHog (as oppose to Mailcatcher) in our integration tests. Love the API and love the "quickness" that comes with Go.

**Pull request merged**
